version: '3.5'
services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    volumes:
      - /mnt/Elements/config:/config
      - /mnt/Elements/cache:/cache
      - /mnt/Elements/media/parents/movies:/media/parents/movies
      - /mnt/Elements/media/parents/shows:/media/parents/shows
      - /mnt/Elements/media/kids/movies:/media/kids/movies
      - /mnt/Elements/media/kids/shows:/media/kids/shows
    ports:
      - 8096:8096
    restart: 'unless-stopped'
    environment:
      - TZ=America/New_York